package com.centersoft.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.centersoft.entity.Bodies;
import com.centersoft.entity.User;
import com.centersoft.entity.VFMessage;

import com.centersoft.dao.BodiesDao;
import com.centersoft.dao.UserDao;
import com.centersoft.dao.VFMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bodiesDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig vFMessageDaoConfig;

    private final BodiesDao bodiesDao;
    private final UserDao userDao;
    private final VFMessageDao vFMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bodiesDaoConfig = daoConfigMap.get(BodiesDao.class).clone();
        bodiesDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        vFMessageDaoConfig = daoConfigMap.get(VFMessageDao.class).clone();
        vFMessageDaoConfig.initIdentityScope(type);

        bodiesDao = new BodiesDao(bodiesDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        vFMessageDao = new VFMessageDao(vFMessageDaoConfig, this);

        registerDao(Bodies.class, bodiesDao);
        registerDao(User.class, userDao);
        registerDao(VFMessage.class, vFMessageDao);
    }
    
    public void clear() {
        bodiesDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        vFMessageDaoConfig.clearIdentityScope();
    }

    public BodiesDao getBodiesDao() {
        return bodiesDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public VFMessageDao getVFMessageDao() {
        return vFMessageDao;
    }

}
